spring.datasource.url=jdbc:postgresql://localhost:5433/rent-accomodations
spring.datasource.username=emc
spring.datasource.password=emc

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

springdoc.swagger-ui.path=/swagger-ui.html

server.port=8081
