spring.application.name=emt-lab
spring.profiles.active=dev

spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET}
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer 